eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/,http://eureka-secondary:8882/eureka/
---
spring:
  profiles: invoicing

---
spring:
  profiles: order

---
spring:
  profiles: shipping

