eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/,http://eureka-secondary:8882/eureka/
---
spring:
  application:
    name: ms-saleorder

---
spring:
  application:
    name: ms-shipping

---
spring:
  application:
    name: ms-invoicing

